export const navLinks = [
    { name: 'Home', path: '/' },
    { name: 'Explore', path: '/explore' },
    { name: 'Categories', path: '/categories' },
]
export const categories = [
    "Fashion",
    "Beauty",
    "Travel",
    "Lifestyle",
    "Personal",
    "Tech",
    "Health",
    "Fitness",
    "Wellness",
    "SaaS",
    "Business",
    "Education",
    "Food and Recipe ",
    "Love and Relationships",
    "Alternative topics",
    "Green living",
    "Music",
    "Automotive",
    "Marketing",
    "Internet services",
    "Finance",
    "Sports",
    "Entertainment",
    "Productivity",
    "Hobbies",
    "Parenting",
    "Pets",
    "Photography",
    "Agriculture",
    "Art",
    "DIY",
    "Science",
    "Gaming",
    "History",
    "Self - improvement",
    "News and current affairs",
];
